# Generated by Django 6.0.1 on 2026-01-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgedocument_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='embedding',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='culture',
            field=models.CharField(choices=[('riz', 'Riz')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
