# Generated by Django 6.0.2 on 2026-02-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_cachedanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='source',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedanswer',
            name='question_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
