# Generated by Django 6.0.2 on 2026-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_remove_knowledgedocument_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionhistory',
            old_name='category',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='pinecone_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='theme',
            field=models.CharField(default='général', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
