# Generated by Django 6.0.2 on 2026-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_rename_category_questionhistory_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
