# Generated by Django 6.0.2 on 2026-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_knowledgedocument_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='agronomy_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
