# Generated by Django 6.0.2 on 2026-03-03 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_knowledgedocument_agronomy_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='agronomy_score',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='country',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='pinecone_id',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='embedding_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
